### ISSUE TITLE
[FIX/BUG] Gloves update fix and skins loading bug

### ISSUE THREAD

**Issue by Hasanovsky** [ianlucas/cs2-inventory-simulator-plugin#22]
[FIX]
To fix a bug with updating gloves during spawn, you can issue a random skin to update the gloves.

[BUG]
When you quickly select the team, the skins can't load or update

**Comment by ianlucas** [comment]
For the "bug", it happens when the fetch of the player's inventory takes longer than the player joining the game. Usually in the next spawn it works normally. I have a work in progress solution for it.

For the "fix", I'll have a look, but I don't like much to have to mess with `SetModel`, but I'll give it a try.

Thanks.
